{
 "title": "Kubernetes: Deprecated API Versions",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Adoption Rate",
   "type": "graph",
   "description": "The percentage of releases that use the updated/supported apiVersions",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg((wf_k8s_deployed_releases - wf_k8s_deployed_releases_with_deprecated_api_version) / wf_k8s_deployed_releases {cluster_name=\"$cluster_name\"})",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Deployed Releases",
   "type": "stat",
   "description": "Total number of the deployed releases",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "wf_k8s_deployed_releases{cluster_name=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Deprecated apiVersions",
   "type": "stat",
   "description": "Total number of releases with deprecated apiVersions",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "wf_k8s_deployed_releases_with_deprecated_api_version{cluster_name=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Deprecated apiVersions Percentage",
   "type": "graph",
   "description": "The percentage of releases that use deprecated  apiVersions",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(wf_k8s_deployed_releases_with_deprecated_api_version / wf_k8s_deployed_releases {cluster_name=\"$cluster_name\"})",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Removed apiVersions",
   "type": "stat",
   "description": "Total number of releases with removed apiVersions",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "wf_k8s_deployed_releases_with_removed_api_version{cluster_name=\"$cluster_name\"}"
    }
   ]
  },
  {
   "title": "Removed apiVersions Percentage",
   "type": "graph",
   "description": "The percentage of releases that use removed  apiVersions",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(wf_k8s_deployed_releases_with_removed_api_version / wf_k8s_deployed_releases {cluster_name=\"$cluster_name\"})",
     "legendFormat": "Percentage"
    }
   ]
  },
  { "title": "Job Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cluster Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk (1, wf_k8s_deprecated_versions_info{cluster_name=\"$cluster_name\"})",
     "legendFormat": "{{k8s_version}}"
    }
   ]
  },
  {
   "title": "Job Last Run",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "wf_k8s_deprecated_versions_job_info{cluster_name=\"$cluster_name\"}",
     "legendFormat": "{{last_run}}"
    }
   ]
  },
  {
   "title": "Job duration in seconds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "wf_k8s_deprecated_versions_job_info{cluster_name=\"$cluster_name\"}",
     "legendFormat": "{{duration_seconds}}"
    }
   ]
  },
  { "title": "Cluster Deprecations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total deprecated API Versions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\"}) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total deprecated API Versions by Kind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\"}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Top 10 namespaces with deprecated API Versions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total removed API Versions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\", removed=\"true\"}) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total removed API Versions in the next release",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\", removed_in_next_release=\"true\"}) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total removed API Versions in the next 2 releases",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\", removed_in_next_2_releases=\"true\"}) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "System Components Deprecations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total deprecated API Versions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\", namespace=~\"^(kube-)\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total deprecated API Versions by Kind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\", namespace=~\"^(kube-)\"}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Total deprecated API Versions by Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\", namespace=~\"^(kube-)\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total removed API Versions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(1-absent(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\", namespace=~\"^(kube-)\", removed=\"true\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total removed API Versions in the next release",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\", namespace=~\"^(kube-)\", removed_in_next_release=\"true\"}) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total removed API Versions in the next 2 releases",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(wf_k8s_deprecated_versions_info{cluster_name=~\"$cluster_name\", namespace=~\"^(kube-)\", removed_in_next_2_releases=\"true\"}) OR vector(0)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}