name: "Verify Python Wheel"
description: "Verify importing the package doesn't cause an error"
inputs:
  package-import-name:
    description: "Name used to import the package from python code"
    required: true
  packages-dir:
    description: The target directory for distribution
    required: false
    default: dist
runs:
  using: "composite"
  steps:
    - name: "Verify wheel"
      run: "$GITHUB_ACTION_PATH/action.sh ${{ inputs.package-import-name }} ${{ inputs.packages-dir }}"
      shell: "bash"
